
services:
  app:
    build:
      context: ..
      dockerfile: dockerfiles/kleo-backend.Dockerfile
    image: kleo-backend
    container_name: kleo-backend
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"